#docker compose up -d
#docker compose down -v
# ver se ta rodando:  docker ps -a 
#apaga tudo: docker system prune -a --volumes

version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: catalogo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: